# Generated by Django 2.2.12 on 2020-04-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('usename', models.CharField(max_length=32, unique=True)),
                ('fname', models.CharField(max_length=32)),
                ('lname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('pw', models.CharField(max_length=256)),
            ],
        ),
    ]
