# Generated by Django 3.0.5 on 2020-04-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200423_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='users/profile_pics'),
        ),
    ]
