# Generated by Django 3.0.5 on 2020-04-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200423_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='site',
        ),
    ]
